language: c
sudo: false

branches:
  only:
    - master

install:
  - source devtools/travis-ci/install.sh
  - export PYTHONUNBUFFERED=true
  # Add org channel
  - conda config --add channels ${ORGNAME}

script:
  # Select the desired python version
  - conda install --yes python=$python
  # Add conda channels
  - conda config --add channels omnia --add channels conda-forge
  # Force update now that conda-forge has been added
  - conda update --yes conda
  # Add openmm dev build
  - conda config --add channels omnia/label/dev
  # Add AMBER channel
  - conda config --add channels http://ambermd.org/downloads/ambertools/conda/
  # Install extras for testing
  - conda install --yes --quiet pip nose nose-timer
  # Workaround for failure to install these when installing local package
  - conda install --yes openmm>=7.2.0 yaml pyyaml ambertools==18 lxml networkx
  # Install AmberTools18
  - conda install ambertools=18 -c http://ambermd.org/downloads/ambertools/conda/
  # Update parmed
  # TODO: Update this when branch is merged
  - pip uninstall --yes parmed
  - pip install git+https://github.com/jchodera/ParmEd.git@fix-patch-equivalence
  # Build the recipe
  - echo "Building the recipe..."
  - conda build devtools/conda-recipe
  # Install the package
  - echo "Installing the ${PACKAGENAME} package..."
  - conda install --yes --use-local ${PACKAGENAME}
  # Test the openmmforcefields package to make sure installed ffxml files are working
  - echo "Testing the installed openmmforcefields ffxml files..."
  - cd devtools && nosetests ${PACKAGENAME}.tests.test_amber_import --nocapture --verbosity=2 --with-timer -a '!slow' && cd ..
  # Test AMBER conversion
  - echo "Testing AMBER conversion..."
  - cd amber && python convert_amber.py --verbose && cd ..
  # Test CHARMM conversion
  - echo "Testing CHARMM conversion..."
  # TODO: Find a way to avoid timing out on travis when running full charmm36.yaml conversion below
  - cd charmm && python convert_charmm.py --verbose --in files/waters.yaml && python convert_charmm.py --verbose --in files/charmm36.yaml && cd ..
  #- cd charmm && python convert_charmm.py --verbose && cd ..
  - cd charmm && python test_charmm.py --verbose && cd ..

os:
  #- osx # LEaP segfaults on osx under some conditions
  - linux

env:
  matrix:
    - python=2.7  CONDA_PY=2.7
    - python=3.5  CONDA_PY=3.5
    - python=3.5  CONDA_PY=3.6

  global:
    - ORGNAME="omnia"
    - PACKAGENAME="openmmforcefields"
