language: python

# Run jobs on container-based infrastructure, can be overridden per job

env:
  global:
    - OE_LICENSE="$TRAVIS_BUILD_DIR/devtools/travis-ci/oe_license.txt"

matrix:
  include:
    # Extra includes for OSX since python language is not available by default on OSX
    - os: osx
      language: generic
      env: PYTHON_VER=3.6
    - os: osx
      language: generic
      env: PYTHON_VER=3.7


    - os: linux
      language: generic  # No need to set Python version since its conda
      env: PYTHON_VER=3.6
    - os: linux
      language: generic
      env: PYTHON_VER=3.7


before_install:
    # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

    # Install the Python environment
  - source devtools/travis-ci/before_install.sh
  - python -V

    # Decrypt OpenEye license
  - openssl aes-256-cbc -K $encrypted_c0daf35c25ce_key -iv $encrypted_c0daf35c25ce_iv -in devtools/travis-ci/oe_license.txt.enc -out devtools/travis-ci/oe_license.txt -d

install:

    # Create test environment for package
  - python devtools/scripts/create_conda_env.py -n=test -p=$PYTHON_VER devtools/conda-envs/test_env.yaml
    # Activate the test environment
  - conda activate test
    # DEBUG
  - echo "OE_LICENSE path:"
  - echo $OE_LICENSE
    # Workaround for https://github.com/openmm/openmm/pull/2511
    # TODO: Remove this when OpenMM builds including https://github.com/openmm/openmm/pull/2511 are released
  - echo "Overwriting OpenMM forcefield.py with fix from https://github.com/openmm/openmm/pull/2511"
  - wget -q https://raw.githubusercontent.com/openmm/openmm/4f48402f1be3e0f049ae0e8595db638d297b0d75/wrappers/python/simtk/openmm/app/forcefield.py -O `python -c "from simtk.openmm.app import forcefield; print(forcefield.__file__)"`
    # Build and install package
    # Can't use 'develop' mode because we remove symlinks after install is complete
    #- python setup.py develop --no-deps
  - python setup.py install


script:
    # Test installed package
  #- pytest -v --cov=openmmforcefields openmmforcefields/tests
  - pytest -v -x -s --log-cli-level INFO --cov=openmmforcefields openmmforcefields/tests/test_amber_import.py
  - pytest -v -x -s --log-cli-level INFO --cov=openmmforcefields openmmforcefields/tests/test_template_generators.py

    # Store current working directory
  - export WORK=`pwd`

    # Test AMBER conversion
  - echo "Testing AMBER conversion..."
  - cd $WORK/amber && python convert_amber.py --input gaff.yaml --log gaff-tests.csv --verbose

    # Test CHARMM conversion
  - echo "Testing CHARMM conversion..."
    # TODO: Find a way to avoid timing out on travis when running full charmm36.yaml conversion below
    #- cd $WORK/charmm && python convert_charmm.py --verbose --in files/waters.yaml && python convert_charmm.py --verbose --in files/charmm36.yaml
  - cd $WORK/charmm && python convert_charmm.py --verbose --in files/waters.yaml
    #- cd charmm && python convert_charmm.py --verbose && cd ..
    # TODO: Uncomment this when tests are expected to work
  #- cd $WORK/charmm && python test_charmm.py --verbose


notifications:
    email: false

after_success:
  - codecov
