package:
  name: openmmforcefields
  version: 0.0.0

source:
  path: ../..

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python

  run:
    - python
    - openmm >=7.2.0
    - parmed
    - pyyaml
    - ambertools ==17
    - lxml

test:
  requires:
    - nose
    - nose-timer
  imports:
    - openmmforcefields

about:
  home: https://github.com/choderalab/openmm-forcefields
  license: MIT License
